name: fluuky
description: "Fluuky"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^17.2.1+1
  get: ^4.6.6
  # google_fonts: ^6.2.1
  hive: ^2.2.3
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  retrofit: '>=4.0.0 <5.0.0'
  logger: any
  json_annotation: ^4.8.1
  dio: ^5.5.0+1
  lottie: ^3.1.2
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.3
  smooth_page_indicator: ^1.1.0
  carousel_slider_plus: ^7.0.0
  http: ^1.2.1
  flutter_form_builder: ^9.2.1
  flutter_secure_storage: ^9.2.2
  injectable: ^2.4.2
  pinput: ^5.0.0
  intl_phone_number_input: ^0.7.4
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.0
  flutter_cache_manager: ^3.4.0
  get_storage:
  dotted_line: ^3.2.2
  dotted_border: ^2.1.0
  flutter_native_splash: ^2.4.0
  dropdown_button2: ^2.3.9
  skeletonizer: ^1.4.2
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  timeago: ^3.7.0
  intl: ^0.19.0
  share_plus: ^10.0.0
  to_arabic_number: ^1.0.1
  jhijri: ^1.0.0
  easy_refresh: ^3.4.0
  flutter_screenutil: ^5.9.3
  email_validator: ^3.0.0
  # rive: ^0.13.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: '>=7.0.0 <8.0.0'
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1

  build_runner: ^2.4.12
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true

  fonts:
      - family: Causten
        fonts:
          - asset: assets/fonts/Causten-Round/Causten-ExtraLight.otf
            weight: 100
          - asset: assets/fonts/Causten-Round/Causten-Light.otf
            weight: 300
          - asset: assets/fonts/Causten-Round/Causten-Medium.otf
            weight: 500
          - asset: assets/fonts/Causten-Round/Causten-Bold.otf
            weight: 700
          - asset: assets/fonts/Causten-Round/Causten-Black.otf
            weight: 900
      - family: Brinnan
        fonts:
          - asset: assets/fonts/Brinnan/Brinnan-Light.ttf
            weight: 300
          - asset: assets/fonts/Brinnan/Brinnan-Regular.ttf
            weight: 500
          - asset: assets/fonts/Brinnan/Brinnan-Bold.ttf
            weight: 700
          - asset: assets/fonts/Brinnan/Brinnan-Black.ttf
            weight: 900
      - family: Cairo
        fonts:
          - asset: assets/fonts/Cairo/Cairo-ExtraLight.woff
            weight: 100
          - asset: assets/fonts/Cairo/Cairo-Light.woff
            weight: 300
          - asset: assets/fonts/Cairo/Cairo-Medium.woff
            weight: 500
          - asset: assets/fonts/Cairo/Cairo-Bold.woff
            weight: 700
          - asset: assets/fonts/Cairo/Cairo-Black.woff
            weight: 900

  assets:
    - assets/lottie/
    - assets/images/
    - assets/credit-cards/
    - assets/flags/
    - assets/languages/
    - assets/mock_responses/
